# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created: Wed Feb 22 23:26:50 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName(_fromUtf8("loginWindow"))
        loginWindow.resize(525, 384)
        loginWindow.setMouseTracking(False)
        loginWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        loginWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        loginWindow.setSizeGripEnabled(False)
        self.registerTab = QtGui.QTabWidget(loginWindow)
        self.registerTab.setGeometry(QtCore.QRect(210, 20, 291, 331))
        self.registerTab.setObjectName(_fromUtf8("registerTab"))
        self.loginTab = QtGui.QWidget()
        self.loginTab.setObjectName(_fromUtf8("loginTab"))
        self.layoutWidget = QtGui.QWidget(self.loginTab)
        self.layoutWidget.setGeometry(QtCore.QRect(34, 160, 221, 30))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.loginButton = QtGui.QPushButton(self.layoutWidget)
        self.loginButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.loginButton.setObjectName(_fromUtf8("loginButton"))
        self.horizontalLayout_3.addWidget(self.loginButton)
        self.findButton = QtGui.QPushButton(self.layoutWidget)
        self.findButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.findButton.setObjectName(_fromUtf8("findButton"))
        self.horizontalLayout_3.addWidget(self.findButton)
        self.layoutWidget1 = QtGui.QWidget(self.loginTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 11, 241, 111))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.accountLable = QtGui.QLabel(self.layoutWidget1)
        self.accountLable.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.accountLable.setObjectName(_fromUtf8("accountLable"))
        self.horizontalLayout_2.addWidget(self.accountLable)
        self.accountLine = QtGui.QLineEdit(self.layoutWidget1)
        self.accountLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.accountLine.setText(_fromUtf8(""))
        self.accountLine.setObjectName(_fromUtf8("accountLine"))
        self.horizontalLayout_2.addWidget(self.accountLine)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.passwordLable = QtGui.QLabel(self.layoutWidget1)
        self.passwordLable.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.passwordLable.setObjectName(_fromUtf8("passwordLable"))
        self.horizontalLayout.addWidget(self.passwordLable)
        self.passwordLine = QtGui.QLineEdit(self.layoutWidget1)
        self.passwordLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.passwordLine.setObjectName(_fromUtf8("passwordLine"))
        self.horizontalLayout.addWidget(self.passwordLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.registerTab.addTab(self.loginTab, _fromUtf8(""))
        self.registerTab_2 = QtGui.QWidget()
        self.registerTab_2.setObjectName(_fromUtf8("registerTab_2"))
        self.layoutWidget2 = QtGui.QWidget(self.registerTab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 31, 271, 241))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.registeraccount = QtGui.QLineEdit(self.layoutWidget2)
        self.registeraccount.setObjectName(_fromUtf8("registeraccount"))
        self.horizontalLayout_4.addWidget(self.registeraccount)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.registerpsd = QtGui.QLineEdit(self.layoutWidget2)
        self.registerpsd.setObjectName(_fromUtf8("registerpsd"))
        self.horizontalLayout_5.addWidget(self.registerpsd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.registercon = QtGui.QLineEdit(self.layoutWidget2)
        self.registercon.setObjectName(_fromUtf8("registercon"))
        self.horizontalLayout_6.addWidget(self.registercon)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.mailLabel = QtGui.QLabel(self.layoutWidget2)
        self.mailLabel.setObjectName(_fromUtf8("mailLabel"))
        self.horizontalLayout_7.addWidget(self.mailLabel)
        self.mailEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.mailEdit.setObjectName(_fromUtf8("mailEdit"))
        self.horizontalLayout_7.addWidget(self.mailEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.registerButton = QtGui.QPushButton(self.layoutWidget2)
        self.registerButton.setObjectName(_fromUtf8("registerButton"))
        self.horizontalLayout_8.addWidget(self.registerButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.registerTab.addTab(self.registerTab_2, _fromUtf8(""))
        self.welcomeLabel = QtGui.QLabel(loginWindow)
        self.welcomeLabel.setGeometry(QtCore.QRect(30, 150, 161, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(12)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setObjectName(_fromUtf8("welcomeLabel"))
        self.accountLable.setBuddy(self.accountLine)
        self.passwordLable.setBuddy(self.passwordLine)
        self.label.setBuddy(self.registeraccount)
        self.label_2.setBuddy(self.registerpsd)
        self.label_3.setBuddy(self.registercon)

        self.retranslateUi(loginWindow)
        self.registerTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.loginButton, QtCore.SIGNAL(_fromUtf8("clicked()")), loginWindow.login)
        QtCore.QObject.connect(self.findButton, QtCore.SIGNAL(_fromUtf8("clicked()")), loginWindow.find)
        QtCore.QObject.connect(self.registerButton, QtCore.SIGNAL(_fromUtf8("clicked()")), loginWindow.register)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        loginWindow.setWindowTitle(_translate("loginWindow", "LETSGO", None))
        self.loginButton.setText(_translate("loginWindow", "登录(&l)", None))
        self.findButton.setText(_translate("loginWindow", "忘记密码(&f)", None))
        self.accountLable.setText(_translate("loginWindow", "账户(&a)", None))
        self.passwordLable.setText(_translate("loginWindow", "密码(&p)", None))
        self.registerTab.setTabText(self.registerTab.indexOf(self.loginTab), _translate("loginWindow", "登录", None))
        self.label.setText(_translate("loginWindow", "账户(&a)", None))
        self.label_2.setText(_translate("loginWindow", "密码(&p)", None))
        self.label_3.setText(_translate("loginWindow", "确认密码(&c)", None))
        self.mailLabel.setText(_translate("loginWindow", "邮箱", None))
        self.registerButton.setText(_translate("loginWindow", "注册(&r)", None))
        self.registerTab.setTabText(self.registerTab.indexOf(self.registerTab_2), _translate("loginWindow", "注册", None))
        self.welcomeLabel.setText(_translate("loginWindow", "欢迎使用LETSGO!", None))

